### ISSUE TITLE
How to include Python standard library

### ISSUE THREAD

**Issue by hanung665** [mwilliamson/stickytape#29]
Let say I'w like to flatify F:/a.py

```
import requests
import re
come codes here
```
and the Python+it libs are in C:/anaconda3

Should I use: F:/> stickytape a.py --add-python-path C:/anaconda3 --output-file F:/a-flatified.py or how?

I've tried different arguments but a.py still contains 'import requests' and 'import re'.

**Comment by mwilliamson** [comment]
It's been a while since I've worked on stickytape, but if memory serves, the way it works is by writing out the modules to disk when the script is run, so the imports still being in the script is expected behaviour.

Also, given it's essentially a big ball of hacks, I'd strongly suggest using an alternative.
