### ISSUE TITLE
Renaming of modules

### ISSUE THREAD

**Issue by tjpalmer** [mwilliamson/stickytape#30]
I'd like to be able to rename the included modules. Since they are found via imports, seems like it ought to be possible to rewrite the imports and the paths.

Motivation would be to avoid name conflicts.

Is this reasonable?

**Comment by mwilliamson** [comment]
Could you explain a bit more about the name conflicts you'd get otherwise?

I'd also suggest that there are likely better tools than stickytape to use, depending on your use case, such as zipapp or PyInstaller.

**Comment by tjpalmer** [comment]
Thanks for the reply!

Specifically, I'm writing a Pygments lexer, but I'm depending on 3rd party packages. Code isn't public right now (though I expect it to be in the future), so I can't show specifics easily. Anyway, given [current examples](https://github.com/pygments/pygments/blob/master/pygments/lexers/jvm.py), I suspect they aren't terribly interested in adding 3rd party dependencies for arbitrary lexers. So I figure a single-file bundler might be more acceptable to them.

None of this is a rush, but I was investigating options, and stickytape seems like one of the better ones.

But it looks to me like stickytape adds the bundled things generally such that they are in the virtual python path for all other modules as well. If this is correct, it would be nice to rename them to some subpackage so they don't get exposed generally. But maybe I've misinterpreted this.

If this is ever meaningful, I might also be interested in multiline rendering of the bundled strings, so it's easier to review the included code.

**Comment by mwilliamson** [comment]
If you want to rename modules, then you probably want to use another tool to vendorise dependencies. I wrote one, [python-vendorize](https://github.com/mwilliamson/python-vendorize), a long time ago, but there are likely better maintained tools out there that do so.

Having said that, I can't say I know much about contributing to Pygments, but I can't imagine they'd be keen to accept to a Python module that, as part of its execution, rewrites the Python path and writes modules out to disk. I'd assume they'd prefer third-party dependencies to be referred to in the usual way rather than embedded in their source code?

Plus, I've been playing around with using zipapp instead of the current approach, which would produce a binary file rather than the current text file.

**Comment by tjpalmer** [comment]
Yeah, you're probably right about them not being happy with that. I'm mostly just exploring options. Thanks much for the tips! I'll go ahead and close this issue.
